const gen = {'HLA-A1': [],
'HLA-A2': [],
'HLA-A*0201': [{'peptide': 'TLIVNSVLL', 'value': 21.36},
 {'peptide': 'IVNSVLLFL', 'value': 40.2},
 {'peptide': 'SVLLFLAFV', 'value': 1082.41},
 {'peptide': 'VLLFLAFVV', 'value': 1040.33},
 {'peptide': 'FLAFVVFLL', 'value': 1310.88},
 {'peptide': 'FVVFLLVTL', 'value': 19.78},
 {'peptide': 'FLLVTLAIL', 'value': 342.86},
 {'peptide': 'SLVKPSFYV', 'value': 2218.71},
 {'peptide': 'YVYSRVKNL', 'value': 63.28}],
'HLA-A*0205': [{'peptide': 'FVSEETGTL', 'value': 126.0},
 {'peptide': 'IVNSVLLFL', 'value': 47.6},
 {'peptide': 'SVLLFLAFV', 'value': 48.0},
 {'peptide': 'VLLFLAFVV', 'value': 12.24},
 {'peptide': 'FLAFVVFLL', 'value': 50.4},
 {'peptide': 'FVVFLLVTL', 'value': 84.0},
 {'peptide': 'VVFLLVTLA', 'value': 10.2},
 {'peptide': 'FLLVTLAIL', 'value': 126.0},
 {'peptide': 'YVYSRVKNL', 'value': 252.0}],
'HLA-A*1101': [{'peptide': 'NIVNVSLVK', 'value': 1.2},
 {'peptide': 'RVKNLNSSR', 'value': 1.2}],
'HLA-A24': [{'peptide': 'GTLIVNSVL', 'value': 8.4},
 {'peptide': 'IVNSVLLFL', 'value': 8.4},
 {'peptide': 'LFLAFVVFL', 'value': 30.0},
 {'peptide': 'VFLLVTLAI', 'value': 10.5},
 {'peptide': 'VTLAILTAL', 'value': 8.4},
 {'peptide': 'CCNIVNVSL', 'value': 8.4},
 {'peptide': 'FYVYSRVKN', 'value': 8.25},
 {'peptide': 'VYSRVKNLN', 'value': 8.4}],
'HLA-A3': [{'peptide': 'LLFLAFVVF', 'value': 30.0},
 {'peptide': 'FLAFVVFLL', 'value': 8.1},
 {'peptide': 'TLAILTALR', 'value': 4.0},
 {'peptide': 'NIVNVSLVK', 'value': 9.0},
 {'peptide': 'LVKPSFYVY', 'value': 5.4},
 {'peptide': 'KPSFYVYSR', 'value': 3.24}],
'HLA-A*3101': [{'peptide': 'TLAILTALR', 'value': 2.0},
 {'peptide': 'KPSFYVYSR', 'value': 6.0},
 {'peptide': 'RVKNLNSSR', 'value': 6.0}],
'HLA-A*3302': [{'peptide': 'TLAILTALR', 'value': 9.0},
 {'peptide': 'RVKNLNSSR', 'value': 4.5}],
'HLA-A68.1': [{'peptide': 'RVKNLNSSR', 'value': 200.0}],
'HLA-A20 Cattle': [{'peptide': 'TLAILTALR', 'value': 120.0},
 {'peptide': 'VKPSFYVYS', 'value': 100.0},
 {'peptide': 'VKNLNSSRV', 'value': 300.0}],
'HLA-A2.1': [],
'HLA-B14': [{'peptide': 'FVVFLLVTL', 'value': 9.0},
 {'peptide': 'FLLVTLAIL', 'value': 15.0},
 {'peptide': 'VTLAILTAL', 'value': 22.5},
 {'peptide': 'YVYSRVKNL', 'value': 100.0},
 {'peptide': 'SRVKNLNSS', 'value': 9.0},
 {'peptide': 'LNSSRVPDL', 'value': 20.0}],
'HLA-B*2702': [{'peptide': 'LLFLAFVVF', 'value': 15.0},
 {'peptide': 'LRLCAYCCN', 'value': 10.0},
 {'peptide': 'SRVKNLNSS', 'value': 10.0}],
'HLA-B*2705': [{'peptide': 'LLFLAFVVF', 'value': 75.0},
 {'peptide': 'LRLCAYCCN', 'value': 200.0},
 {'peptide': 'SRVKNLNSS', 'value': 200.0}],
'HLA-B*3501': [{'peptide': 'VSLVKPSFY', 'value': 10.0},
 {'peptide': 'LVKPSFYVY', 'value': 6.0}],
'HLA-B*3701': [{'peptide': 'VSEETGTLI', 'value': 5.0},
 {'peptide': 'TLIVNSVLL', 'value': 5.0},
 {'peptide': 'IVNSVLLFL', 'value': 7.5},
 {'peptide': 'LFLAFVVFL', 'value': 5.0},
 {'peptide': 'FLAFVVFLL', 'value': 7.5},
 {'peptide': 'NSSRVPDLL', 'value': 7.5}],
'HLA-B*3801': [],
'HLA-B*3901': [{'peptide': 'LFLAFVVFL', 'value': 9.0},
 {'peptide': 'FVVFLLVTL', 'value': 9.0},
 {'peptide': 'FLLVTLAIL', 'value': 9.0},
 {'peptide': 'VTLAILTAL', 'value': 9.0},
 {'peptide': 'YVYSRVKNL', 'value': 9.0}],
'HLA-B*3902': [{'peptide': 'GTLIVNSVL', 'value': 2.4},
 {'peptide': 'IVNSVLLFL', 'value': 2.4},
 {'peptide': 'LFLAFVVFL', 'value': 2.4},
 {'peptide': 'FLAFVVFLL', 'value': 2.4},
 {'peptide': 'FVVFLLVTL', 'value': 2.4},
 {'peptide': 'VTLAILTAL', 'value': 2.4},
 {'peptide': 'CCNIVNVSL', 'value': 2.4},
 {'peptide': 'NSSRVPDLL', 'value': 2.4}],
'HLA-B40': [{'peptide': 'SEETGTLIV', 'value': 2.0},
 {'peptide': 'GTLIVNSVL', 'value': 2.0},
 {'peptide': 'LAILTALRL', 'value': 2.0}],
'HLA-B*4403': [{'peptide': 'SEETGTLIV', 'value': 12.0},
 {'peptide': 'LTALRLCAY', 'value': 9.0},
 {'peptide': 'VSLVKPSFY', 'value': 9.0}],
'HLA-B*5101': [{'peptide': 'TGTLIVNSV', 'value': 44.0},
 {'peptide': 'LAFVVFLLV', 'value': 314.6},
 {'peptide': 'LAILTALRL', 'value': 71.5}],
'HLA-B*5102': [{'peptide': 'LAFVVFLLV', 'value': 550.0},
 {'peptide': 'LAILTALRL', 'value': 363.0}],
'HLA-B*5103': [{'peptide': 'TGTLIVNSV', 'value': 48.4},
 {'peptide': 'LAFVVFLLV', 'value': 145.2},
 {'peptide': 'LAILTALRL', 'value': 16.5}],
'HLA-B*5201': [{'peptide': 'VLLFLAFVV', 'value': 60.0},
 {'peptide': 'LLFLAFVVF', 'value': 67.5},
 {'peptide': 'LAFVVFLLV', 'value': 18.0}],
'HLA-B*5301': [],
'HLA-B*5401': [],
'HLA-B*51': [],
'HLA-B*5801': [{'peptide': 'VSEETGTLI', 'value': 4.0},
 {'peptide': 'NSVLLFLAF', 'value': 79.2},
 {'peptide': 'LTALRLCAY', 'value': 7.2},
 {'peptide': 'VSLVKPSFY', 'value': 6.0}],
'HLA-B60': [{'peptide': 'SEETGTLIV', 'value': 16.0},
 {'peptide': 'GTLIVNSVL', 'value': 8.8},
 {'peptide': 'VTLAILTAL', 'value': 8.8},
 {'peptide': 'LAILTALRL', 'value': 17.6},
 {'peptide': 'CCNIVNVSL', 'value': 8.8},
 {'peptide': 'NSSRVPDLL', 'value': 8.8}],
'HLA-B61': [{'peptide': 'SEETGTLIV', 'value': 40.0},
 {'peptide': 'EETGTLIVN', 'value': 2.4},
 {'peptide': 'TGTLIVNSV', 'value': 2.0},
 {'peptide': 'LAFVVFLLV', 'value': 3.0},
 {'peptide': 'LCAYCCNIV', 'value': 2.0},
 {'peptide': 'CNIVNVSLV', 'value': 2.0}],
'HLA-B62': [{'peptide': 'LIVNSVLLF', 'value': 12.0},
 {'peptide': 'LLFLAFVVF', 'value': 52.8},
 {'peptide': 'ALRLCAYCC', 'value': 6.0},
 {'peptide': 'LVKPSFYVY', 'value': 7.92}],
'HLA-B7': [{'peptide': 'FVSEETGTL', 'value': 20.0},
 {'peptide': 'IVNSVLLFL', 'value': 20.0},
 {'peptide': 'FVVFLLVTL', 'value': 20.0},
 {'peptide': 'LAILTALRL', 'value': 12.0},
 {'peptide': 'YVYSRVKNL', 'value': 20.0}],
'HLA-B*0702': [],
'HLA-B8': [{'peptide': 'YVYSRVKNL', 'value': 4.0},
 {'peptide': 'YSRVKNLNS', 'value': 2.0},
 {'peptide': 'LNSSRVPDL', 'value': 4.0}],
'HLA-Cw*0301': [{'peptide': 'GTLIVNSVL', 'value': 24.0},
 {'peptide': 'TLIVNSVLL', 'value': 24.0},
 {'peptide': 'NSVLLFLAF', 'value': 25.0},
 {'peptide': 'LFLAFVVFL', 'value': 20.0},
 {'peptide': 'FVVFLLVTL', 'value': 24.0},
 {'peptide': 'FLLVTLAIL', 'value': 20.0},
 {'peptide': 'VTLAILTAL', 'value': 20.0},
 {'peptide': 'LAILTALRL', 'value': 40.0},
 {'peptide': 'YVYSRVKNL', 'value': 24.0}],
'HLA-Cw*0401': [{'peptide': 'LFLAFVVFL', 'value': 400.0},
 {'peptide': 'AFVVFLLVT', 'value': 10.0},
 {'peptide': 'VFLLVTLAI', 'value': 25.0},
 {'peptide': 'FLLVTLAIL', 'value': 11.52},
 {'peptide': 'AYCCNIVNV', 'value': 50.0}],
'HLA-Cw*0602': [{'peptide': 'TGTLIVNSV', 'value': 6.6},
 {'peptide': 'SVLLFLAFV', 'value': 6.0},
 {'peptide': 'LFLAFVVFL', 'value': 12.0},
 {'peptide': 'FVVFLLVTL', 'value': 13.2},
 {'peptide': 'VTLAILTAL', 'value': 12.0}],
'HLA-Cw*0702': [],
'H2-Db': [{'peptide': 'TLIVNSVLL', 'value': 792.0},
 {'peptide': 'FLLVTLAIL', 'value': 9.5},
 {'peptide': 'AYCCNIVNV', 'value': 11.0},
 {'peptide': 'CNIVNVSLV', 'value': 36.0},
 {'peptide': 'SRVKNLNSS', 'value': 9.5},
 {'peptide': 'VKNLNSSRV', 'value': 11.0}],
'H2-Db revised': [{'peptide': 'TLIVNSVLL', 'value': 1580.71},
 {'peptide': 'FVVFLLVTL', 'value': 36.32},
 {'peptide': 'CNIVNVSLV', 'value': 31.36},
 {'peptide': 'NSSRVPDLL', 'value': 30.86}],
'H2-Dd': [{'peptide': 'TGTLIVNSV', 'value': 6.0},
 {'peptide': 'YVYSRVKNL', 'value': 6.0}],
'H2-Kb': [{'peptide': 'YVYSRVKNL', 'value': 6.0}],
'H2-Kd': [{'peptide': 'LFLAFVVFL', 'value': 1920.0},
 {'peptide': 'VFLLVTLAI', 'value': 1920.0},
 {'peptide': 'VTLAILTAL', 'value': 138.24},
 {'peptide': 'AYCCNIVNV', 'value': 720.0},
 {'peptide': 'FYVYSRVKN', 'value': 120.0}],
'H2-Kk': [{'peptide': 'SEETGTLIV', 'value': 100.0},
 {'peptide': 'EETGTLIVN', 'value': 20.0},
 {'peptide': 'VFLLVTLAI', 'value': 15.0}],
'H2-Ld': [{'peptide': 'LIVNSVLLF', 'value': 10.0},
 {'peptide': 'NSVLLFLAF', 'value': 50.0},
 {'peptide': 'LLFLAFVVF', 'value': 10.0},
 {'peptide': 'NVSLVKPSF', 'value': 10.0},
 {'peptide': 'VSLVKPSFY', 'value': 10.0},
 {'peptide': 'NSSRVPDLL', 'value': 25.0}]}

  export default gen;